version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: ironlog-mongo
    ports:
      - "27017:27017"                   
    environment:
      MONGO_INITDB_DATABASE: ironlog    
    volumes:
      - mongodb_data:/data/db          

volumes:
  mongodb_data:
